import type { NextPage } from 'next'
import { signIn, useSession, signOut } from 'next-auth/react'
import Head from 'next/head'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  const { status, data } = useSession()
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  if (status === 'loading') {
    return <div>Loading ...</div>
  }

  if (status === 'authenticated' && data) {
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name='description' content='Generated by create-t3-app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='flex flex-col items-center justify-center w-full'>
          <h2 className='font-semibold text-red-400'>
            Hello {data.user?.name}
          </h2>
          <button onClick={() => signOut()}>Sign out</button>
        </div>
      </>
    )
  } else {
    return (
      <div>
        Not authenticated
        <button onClick={() => signIn()}>Sign in</button>
      </div>
    )
  }
}

export default Home
